### ISSUE TITLE
Error: Input required and not supplied: token

### ISSUE THREAD

**Issue by chinarut** [everruler12/roam2github#13]
I walked through the [step-by-step instructions](https://github.com/everruler12/roam2github/blob/main/documentation/Full%20Guide%20with%20Step-by-Step%20Screenshots.md) and it seemed all straight forward.

my understanding cron “0 * * * *” means top of the hour - and nothing happened.

so I went into the workflow and found the error:

```
Run actions/checkout@v2 
 with: 
   ssh-strict: true 
   persist-credentials: true 
   clean: true 
   fetch-depth: 1 
   lfs: false 
   submodules: false 
Error: Input required and not supplied: token
```

in main.yml:

```
- uses: actions/checkout@v2
   with: 
     repository: ${{ secrets.BACKUP_REPO }}
     token: ${{ secrets.ACCESS_TOKEN }}
```

I was only prompted to insert 3 keys during setup: ROAM_{EMAIL, PASSWORD, GRAPH}

why is my ACCESS_TOKEN null?
who defines BACKUP_REPO and ACCESS_TOKEN?

I found something called [GITHUB_TOKEN](https://docs.github.com/en/actions/reference/authentication-in-a-workflow)  - not sure if this is something completely different as I’m a bit of a noob when it comes to workflows (and am finding it neat :)
